### ISSUE TITLE
都可以可以跳核吗？

### ISSUE THREAD

**Issue by LHC12580** [DengXiangHong/react-native-alipay-verify#1]

**Comment by Aceris9527** [comment]
不太明白你的意思，都可以是指什么呢，目前该组件支持在react-native app内调起支付宝SDK完成实名认证，组件仅实现了移动端流程，服务端代码需你自己实现，参考官方文档☞https://opendocs.alipay.com/open/20181012100420932508/intro

**Comment by LHC12580** [comment]
简单来说 就是跳过抖音实名认证登录，怎么可以实现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 中午11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DengXiangHong/react-native-alipay-verify] 都可以可以跳核吗？ (Issue #1)




 
不太明白你的意思，都可以是指什么呢，目前该组件支持在react-native app内调起支付宝SDK完成实名认证，组件仅实现了移动端流程，服务端代码需你自己实现，参考官方文档☞https://opendocs.alipay.com/open/20181012100420932508/intro

**Comment by Aceris9527** [comment]
你的意思是绕过抖音APP的实名认证限制吗？

**Comment by LHC12580** [comment]
是的，大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 中午12:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DengXiangHong/react-native-alipay-verify] 都可以可以跳核吗？ (Issue #1)




 
你的意思是绕过抖音APP的实名认证限制吗？
